### ISSUE TITLE
Following the install instructions, even when notebook.zim has the md extension, md files are ignored

### ISSUE THREAD

**Issue by quesada** [pfalcon/zim-desktop-wiki#11]
First, thanks for maintaining this fork. It's truly a godsent.

I've  followed the instruction on the readme.

I have:

default_file_format=zim_markdown
default_file_extension=.md

On notebook.zim.

I still don't get to see md files indexed. 

Since I read you have been using this in production for a while, it might well be that I'm doing something wrong. Do you have any ideas about what I should try?

On step 6, quit zim: do we want to do this before the indexing is complete?

I tried tool > update index and nothing really changes.

**Comment by quesada** [comment]
Never mind, I got it to work by starting with an empty notebook, then adding the md fles

**Comment by quesada** [comment]
Looks like images are not showing. Opening a different issue

**Comment by pfalcon** [comment]
> First, thanks for maintaining this fork.

Well, as of now, "maintaining" is too loud a word, as I didn't update to upstream for a while. I how do you my fork daily.
