### ISSUE TITLE
how to begin with md

### ISSUE THREAD

**Issue by squalou** [pfalcon/zim-desktop-wiki#3]
Hi,

I'm following the original issue https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/26 with great interest,
but didn't want to overload the already quite long discussions there.

First things first : thank you for the effort around this !

I've just cloned your repo to give MD a quick try. (disclaimer : I understand this is WIP, I'm just playing around with not-important data)

When start zim.py, it works fine, just ... like the regular zim. No idea how to start to write with md format. 

Creating a new note does a weird mixup : note the "# test" title, but the file is saved as test.txt 

```md
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2021-02-01T15:12:51+01:00

# test
Created lundi 01 février 2021
```

I probably *did* miss an obvious thing, sorry about that.

Any clue will be welcome :)

**Comment by pfalcon** [comment]
There should have been instructions to activate it for a particular notebook in the ticket you link to, but I guess I need to add instructions to the README in this repo. Will do that when get a chance.

**Comment by pfalcon** [comment]
Ok, https://github.com/pfalcon/zim-desktop-wiki/blob/pfalcon/README.md now starts with instructions on how to use it.

**Comment by squalou** [comment]
Thank you !
