### ISSUE TITLE
Revert formatted page to Markdown

### ISSUE THREAD

**Issue by ghost** [pfalcon/zim-desktop-wiki#5]
Am I missing something, or is there no way once a page has been formatted to return to editing the Markdown code directly? I mean of course one can edit the .md file in an external text editor, but is there no way to do it within Zim?

**Comment by pfalcon** [comment]
> of course one can edit the .md file in an external text editor

If you can do that, why would you need something else? Zim itself is a WYSIWYG editor. There's Tools -> Edit Source to help you call an external editor for the current page.

Generally, this isn't a matter of the Markdown fork, please ask such questions upstream.
